use_frameworks!
platform :ios, '9.0'

target 'iOSMovieDB_Example' do
  pod 'iOSMovieDB', :path => '../'

  target 'iOSMovieDB_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0', :inhibit_warnings => true
    pod 'Nimble', '~> 7.0', :inhibit_warnings => true
  end
end
