use_frameworks!
platform :ios, '9.0'
inhibit_all_warnings!

target 'iOSMovieDB_Example' do
  pod 'iOSMovieDB', :path => '../'

  target 'iOSMovieDB_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
